### ISSUE TITLE
Error using proxy.web

### ISSUE THREAD

**Issue by keithstric** [nxtedition/node-http2-proxy#10]
Up front I apologize for posting this question here, but I couldn't find anywhere else to do so. But, 
I'm attempting to use this to proxy ajax requests to/from another host. However, I'm getting this error when I run index.js:

```
node dist/index.js
/Users/johndoe/rpd/dig-http2-proxy/node_modules/http2-proxy/index.js:22
} = http2.constants
         ^

TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/Users/johndoe/rpd/dig-http2-proxy/node_modules/http2-proxy/index.js:22:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/johndoe/rpd/dig-http2-proxy/dist/index.js:4:13)
    at Module._compile (module.js:624:30)
```

Here is the offending code (index.js):
```
"use strict";

var http2 = require('http2');
var proxy require('http2-proxy');
var fs = require('fs');

var port: 3000;

// Files hard coded for troubleshooting purposes
var serverOptions = {
	target: 'http://shiva.rpd.com',
	allowHTTP1: true,
	key: fs.readFileSync('dist/security/server.key'),
	cert: fs.readFileSync('dist/security/server.crt')
};
var server = http2.createServer(serverOptions);

server.on('request', onRequest);
server.listen(port);

function onRequest(req, res) {
	var proxyOpts = {
		hostname: 'shiva.rpd.com',
		port: 80
	}
	proxy.web(req, res, proxyOpts, (err) => { console.log('Error', err); });
	// res.end('Add a response');
}
```
Now, if I comment out the require('http2-proxy'), proxy.web(req, res....) line and uncomment the res.end() call, this all works (of course with the exception of proxying requests). Also, I tried "http://shiva.rpd.com" and "shiva.rpd.com" as the hostname value in proxyOpts and also no port property with the same result.

Environment:
macOS: 10.12.6
nodejs: 8.5.0

I assume I'm missing something here as I'm a total newb when it comes to nodejs. So, am I missing something or is this a bug?

**Comment by keithstric** [comment]
You must run node with the --expose-http2 option.
