### ISSUE TITLE
Bug with Git clone

### ISSUE THREAD

**Issue by Muhaah** [nxtedition/node-http2-proxy#18]
I'm using your proxy for a Gitlab-Server. 
If i try: `git clone ......` I’m getting this:

```
remote: Counting objects: 3857, done.
remote: Compressing objects: 100% (99/99), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
My Git version is: `2.15.1`

On `node-http-proxy `there is no issue.

**Comment by ronag** [comment]
Could you provide your full command line?

**Comment by Muhaah** [comment]
Thank you for your quick response.

```
git clone https://<myDomain>/<myProject>.git
Cloning into '<myProject>'...
Username for 'https://<myDomain>': <username>
Password for 'https://<user>@<myDomain>': <password>
remote: Counting objects: 3857, done.
remote: Compressing objects: 100% (99/99), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by ronag** [comment]
Works just fine...

```bash
git clone https://github.com/nxtedition/node-http2-proxy.git
Cloning into 'node-http2-proxy'...
remote: Counting objects: 940, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 940 (delta 6), reused 11 (delta 6), pack-reused 927
Receiving objects: 100% (940/940), 181.86 KiB | 393.00 KiB/s, done.
Resolving deltas: 100% (624/624), done.
```

**Comment by Muhaah** [comment]
My setup is a Gitlab-Server behind a reverse-ssl-proxy (node-http2-proxy).
I send you a mail with a repo on my server so you can test it.
In one of ten Git pull commands, I’m getting an error.

**Comment by Muhaah** [comment]
Here is the error from `proxy.web(...).catch((error)=>{console.log(error)})`

```
{ Error: socket hang up
    at createError (......\node_modules\http2-proxy\index.js:375:15)
    at IncomingMessage.onProxyAborted (......\node_modules\http2-proxy\index.js:254:22)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at Socket.socketCloseListener (_http_client.js:353:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12) code: 'ECONNRESET', statusCode: 502 }
```
