### ISSUE TITLE
Can't get Helmet working

### ISSUE THREAD

**Issue by adambiggs** [nxtedition/node-http2-proxy#19]
I tried to add helmet to my `onRes()` handler [as described in the docs](https://github.com/nxtedition/node-http2-proxy#use-helmet-to-secure-response-headers), but every request results in the following error:

```
Error: It appears you have done something like `app.use(helmet)`, but it should be `app.use(helmet())`.
     at helmet (/usr/src/app/node_modules/helmet/index.js:16:11)
     at onRes (/usr/src/app/src/reverse-proxy.js:108:28)
     at ClientRequest.onProxyResponse (/usr/src/app/node_modules/http2-proxy/index.js:239:25)
     at emitOne (events.js:116:13)
     at ClientRequest.emit (events.js:211:7)
     at ClientRequest.emit (/usr/src/app/node_modules/raven/lib/instrumentation/http.js:46:23)
     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
     at Socket.socketOnData (_http_client.js:440:20)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at Socket.Readable.push (_stream_readable.js:208:10)
     at TCP.onread (net.js:594:20)
```

**Comment by ronag** [comment]
You need to instantiate helmet, e.g.

```js
const createHelmet = require('helmet')
const helment = createHelmet()
```
